site_name: MKDocs TEST
site_url: https://sodacrush.github.io
repo_name: sodacrush/sodacrush.github.io
repo_url: https://github.com/sodacrush/sodacrush.github.io

theme:
  name: material
  custom_dir: overrides

use_directory_urls: true

extra_css:
  - stylesheets/extra.css
