site_name: MKDocs TEST
site_url: https://sodacrush.github.io
repo_name: sodacrush/sodacrush.github.io
repo_url: https://github.com/sodacrush/sodacrush.github.io

theme:
  name: material
  custom_dir: overrides

markdown_extensions:
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

use_directory_urls: true

extra_css:
  - stylesheets/extra.css
